import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/utils/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kuis Dan Tebak Gambar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${inter.className}`}>{children}</body>
      </UserProvider>
    </html>
  );
}
